export const LISTING_COPY: Record<string, string> = {
  'p-laptop': '15.6 pulgadas · 16 GB · SSD 512 GB · uso de taller',
  'p-mouse': 'Inalámbrico · 2400 dpi · receptor USB-C',
  'p-libro': 'Edición de mesa · 240 páginas · tapa blanda',
  'p-silla': 'Roble y lino · asiento 45 cm · respaldo bajo',
  'p-tablet': 'Pantalla 11" · lápiz incluido · 256 GB',
  'p-lampara': 'Brazo articulado · LED 2700 K · base de hierro',
  'p-teclado': 'Switches táctiles · layout ES · cable USB-C',
  'p-cuaderno': 'A5 · 120 hojas · papel 90 g',
  'p-atlas': 'Cartografía de oficios · tapa dura · 96 láminas',
  'p-mesa': 'Roble macizo · 180 × 90 cm · aceite natural',
  'p-banqueta': 'Asiento bajo · nogal · 42 cm de alto',
  'p-aparador': 'Dos puertas · 90 cm · herrajes de cobre',
  'p-jarron': 'Gres esmaltado · 28 cm · pieza de torno',
  'p-manta': 'Lana merino · 140 × 200 cm · tejido plano',
  'p-candelabro': 'Cobre martillado · dos brazos · 22 cm',
  'p-delantal': 'Lino lavado · bolsillo cruzado · talla única',
  'p-bufanda': 'Merino peinado · 180 cm · flecos cortos',
  'p-chaqueta': 'Sarga de algodón · talla M · bolsillos de pecho',
}
